Algoritmo "Questao1"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 01/10/2020
Var
numero : inteiro


Inicio
escreva("Digite um numero:")
leia(numero)
se numero > 10 entao
  escreva("É MAIOR QUE 10!")
senao
  escreva("NÃO É MAIOR QUE 10!")
fimse


Fimalgoritmo

